# Generated by Django 3.2.8 on 2021-12-04 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211204_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='event_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
