# Generated by Django 3.2.8 on 2021-12-05 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211204_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='application',
            name='expirience',
        ),
        migrations.RemoveField(
            model_name='application',
            name='medical_cert',
        ),
        migrations.RemoveField(
            model_name='application',
            name='video',
        ),
        migrations.CreateModel(
            name='Stage4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Не отправлено'), (2, 'На рассмотрении'), (3, 'Принято'), (4, 'Отклонено')])),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='Stage3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Не отправлено'), (2, 'На рассмотрении'), (3, 'Принято'), (4, 'Отклонено')])),
                ('contract', models.FileField(blank=True, null=True, upload_to='')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='Stage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Не отправлено'), (2, 'На рассмотрении'), (3, 'Принято'), (4, 'Отклонено')])),
                ('medical_cert', models.FileField(blank=True, null=True, upload_to='')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='Stage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Не отправлено'), (2, 'На рассмотрении'), (3, 'Принято'), (4, 'Отклонено')])),
                ('expirience', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.application')),
            ],
        ),
    ]
