# Generated by Django 3.2.8 on 2021-12-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211205_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage1',
            name='name',
            field=models.CharField(default='Подача заявки', max_length=1000),
        ),
        migrations.AddField(
            model_name='stage2',
            name='name',
            field=models.CharField(default='Медицинские документы', max_length=1000),
        ),
        migrations.AddField(
            model_name='stage3',
            name='name',
            field=models.CharField(default='Подписание договора', max_length=1000),
        ),
        migrations.AddField(
            model_name='stage4',
            name='name',
            field=models.CharField(default='Камчатка!', max_length=1000),
        ),
    ]
